export function openPrintWindow(htmlContent: string, title: string) {
  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(`
    <html><head><title>${escapeHtml(title)}</title>
    <style>
      body { font-family: 'Courier New', monospace; padding: 40px; font-size: 13px; color: #1a1a1a; }
      table { width: 100%; border-collapse: collapse; }
      td { padding: 6px 8px; border-bottom: 1px solid #e5e5e5; }
      td:first-child { color: #737373; width: 40%; }
      td:last-child { font-weight: 600; }
      h1 { font-size: 20px; margin-bottom: 4px; }
      .header { margin-bottom: 24px; border-bottom: 2px solid #1a1a1a; padding-bottom: 12px; }
      .badge { display: inline-block; padding: 2px 10px; border-radius: 4px; font-size: 12px; font-weight: 600; }
      .badge-success { background: #dcfce7; color: #166534; }
      .badge-warning { background: #fef3c7; color: #92400e; }
      .badge-destructive { background: #fee2e2; color: #991b1b; }
      .badge-secondary { background: #f5f5f5; color: #525252; }
      .invoice-table { width: 100%; border-collapse: collapse; margin-top: 12px; }
      .invoice-table th { background: #f5f5f5; padding: 8px; text-align: left; font-size: 12px; border-bottom: 2px solid #1a1a1a; }
      .invoice-table td { padding: 8px; border-bottom: 1px solid #e5e5e5; }
      .invoice-table tr:last-child td { border-bottom: none; }
      .total-row td { font-weight: 700; font-size: 15px; border-top: 2px solid #1a1a1a; padding-top: 10px; }
      .footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #e5e5e5; font-size: 11px; color: #a3a3a3; text-align: center; }
      .logo { max-height: 48px; margin-bottom: 8px; }
      .summary-cards { display: flex; gap: 24px; margin-bottom: 32px; }
      .summary-card { border: 1px solid #ddd; border-radius: 8px; padding: 16px; flex: 1; }
      .summary-card .label { font-size: 11px; color: #666; text-transform: uppercase; }
      .summary-card .value { font-size: 24px; font-weight: 700; margin-top: 4px; }
      @media print { body { padding: 20px; } }
    </style></head><body>
    ${htmlContent}
    </body></html>
  `);
  win.document.close();
  win.print();
}

function escapeHtml(str: string): string {
  return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

export function buildReceiptHtml(options: {
  title: string;
  companyName: string;
  logoUrl?: string | null;
  bodyHtml: string;
  footerText?: string;
}): string {
  const { title, companyName, logoUrl, bodyHtml, footerText } = options;
  return `
    <div class="header">
      ${logoUrl ? `<img src="${escapeHtml(logoUrl)}" class="logo" alt="Logo" />` : ""}
      <h1>${escapeHtml(title)}</h1>
      <p style="color:#737373;font-size:13px">${escapeHtml(companyName)}</p>
    </div>
    ${bodyHtml}
    <div class="footer">${escapeHtml(footerText || `Generated by ${companyName} on ${new Date().toLocaleDateString()}`)}</div>
  `;
}

export function buildFinancialReportHtml(options: {
  companyName: string;
  totalRevenue: string;
  pendingPayouts: string;
  transactionsHtml: string;
  pendingWithdrawalsHtml: string;
}): string {
  const { companyName, totalRevenue, pendingPayouts, transactionsHtml, pendingWithdrawalsHtml } = options;
  return `
    <div class="header">
      <h1>Financial Report</h1>
      <p style="color:#737373;font-size:13px">${escapeHtml(companyName)} — Admin Portal</p>
    </div>

    <div class="summary-cards">
      <div class="summary-card">
        <div class="label">Total Revenue</div>
        <div class="value" style="color:#16a34a">${totalRevenue}</div>
      </div>
      <div class="summary-card">
        <div class="label">Pending Payouts</div>
        <div class="value" style="color:#d97706">${pendingPayouts}</div>
      </div>
    </div>

    <h2 style="font-size:16px;margin-top:32px;margin-bottom:12px">Transactions</h2>
    <table class="invoice-table">
      <thead><tr><th>ID</th><th>Description</th><th>Owner</th><th>Date</th><th style="text-align:right">Amount</th></tr></thead>
      <tbody>${transactionsHtml || '<tr><td colspan="5" style="text-align:center;color:#999">No transactions</td></tr>'}</tbody>
    </table>

    <h2 style="font-size:16px;margin-top:32px;margin-bottom:12px">Pending Withdrawals</h2>
    <table class="invoice-table">
      <thead><tr><th>User</th><th>Email</th><th>Date</th><th>Status</th><th style="text-align:right">Amount</th></tr></thead>
      <tbody>${pendingWithdrawalsHtml || '<tr><td colspan="5" style="text-align:center;color:#999">No pending withdrawals</td></tr>'}</tbody>
    </table>
  `;
}
