"use client";

import { useRef, useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { formatCurrency, formatDateTime } from "@/lib/utils";
import { Printer, Download, X } from "lucide-react";
import { openPrintWindow, buildReceiptHtml } from "@/lib/print";

interface BaseTransaction {
  id: string;
  type?: string;
  amount: number;
  currency?: string;
  description?: string | null;
  reference?: string | null;
  monnifyRef?: string | null;
  balanceBefore?: number | null;
  balanceAfter?: number | null;
  bookingId?: string | null;
  metadata?: Record<string, unknown> | null;
  createdAt: string;
}

interface WithdrawalDetail {
  id: string;
  amount: number;
  destinationBank?: string | null;
  destinationAccount?: string | null;
  accountName?: string | null;
  status: string;
  reference?: string | null;
  monnifyRef?: string | null;
  narration?: string | null;
  processedAt?: string | null;
  createdAt: string;
}

interface TransactionDetailModalProps {
  transaction: BaseTransaction | null;
  withdrawal: WithdrawalDetail | null;
  onClose: () => void;
}

interface Branding {
  companyName: string;
  appName: string;
  logoUrl: string | null;
  contactAddress?: string | null;
  contactPhone?: string | null;
  contactEmail?: string | null;
}

interface BookingItem {
  id: string;
  title: string;
  type: string;
  totalCost: number;
  quantity: number;
  startDate?: string;
  endDate?: string;
}

const statusBadge: Record<string, "warning" | "success" | "destructive" | "default" | "secondary"> = {
  PENDING_OTP: "warning",
  PENDING: "warning",
  PROCESSED: "success",
  APPROVED: "success",
  REJECTED: "destructive",
  FAILED: "destructive",
};

const statusLabel: Record<string, string> = {
  PENDING_OTP: "Awaiting OTP",
  PENDING: "Pending Approval",
  PROCESSED: "Processed",
  APPROVED: "Approved",
  REJECTED: "Rejected",
  FAILED: "Failed",
};

function DetailRow({ label, value, mono }: { label: string; value: string; mono?: boolean }) {
  return (
    <div className="flex justify-between border-b border-neutral-100 py-2 text-sm">
      <span className="text-neutral-500">{label}</span>
      <span className={`font-medium text-neutral-900 ${mono ? "font-mono" : ""}`}>{value}</span>
    </div>
  );
}

export function TransactionDetailModal({ transaction, withdrawal, onClose }: TransactionDetailModalProps) {
  const printRef = useRef<HTMLDivElement>(null);
  const [branding, setBranding] = useState<Branding | null>(null);
  const [bookingItems, setBookingItems] = useState<BookingItem[]>([]);
  const [loadingInvoice, setLoadingInvoice] = useState(false);

  const bookingIds = transaction?.metadata?.bookingIds as string[] | undefined;

  useEffect(() => {
    fetch("/api/settings/public")
      .then((r) => r.json())
      .then((res) => { if (res.success) setBranding(res.data); })
      .catch(() => {});
  }, []);

  useEffect(() => {
    if (!bookingIds || bookingIds.length === 0) return;
    setLoadingInvoice(true);
    Promise.all(
      bookingIds.map((bid) =>
        fetch(`/api/bookings/${bid}`)
          .then((r) => r.json())
          .then((res) => (res.success ? res.data : null))
          .catch(() => null)
      )
    ).then((bookings) => {
      const items: BookingItem[] = bookings
        .filter((b): b is NonNullable<typeof b> => b != null)
        .map((b) => ({
          id: b.id,
          title: b.asset?.title || b.title || "Unknown",
          type: b.asset?.type || b.type || "",
          totalCost: b.totalCost,
          quantity: b.quantity || 1,
          startDate: b.startDate,
          endDate: b.endDate,
        }));
      setBookingItems(items);
      setLoadingInvoice(false);
    });
  }, [bookingIds]);

  const companyName = branding?.companyName || "TruckLease Pro";
  const logoUrl = branding?.logoUrl;

  function handlePrint() {
    const content = printRef.current?.innerHTML || "";
    const html = buildReceiptHtml({
      title: isInvoice ? "Cart Invoice" : "Transaction Receipt",
      companyName,
      logoUrl,
      bodyHtml: content,
      footerText: `Generated by ${companyName} on ${new Date().toLocaleDateString()}`,
    });
    openPrintWindow(html, isInvoice ? "Cart Invoice" : "Transaction Receipt");
  }

  if (!transaction && !withdrawal) return null;

  const isInvoice = !!bookingIds && bookingIds.length > 0;
  const modalRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!transaction && !withdrawal) return;
    const handleKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    document.addEventListener("keydown", handleKey);
    modalRef.current?.focus();
    return () => document.removeEventListener("keydown", handleKey);
  }, [transaction, withdrawal, onClose]);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onClick={onClose}>
      <div ref={modalRef} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="tx-modal-title"
        className="relative w-full max-w-lg rounded-lg bg-white shadow-xl outline-none" onClick={(e) => e.stopPropagation()}>
        <div className="flex items-center justify-between border-b border-neutral-200 px-5 py-3">
          <h2 id="tx-modal-title" className="text-base font-bold text-neutral-900">
            {isInvoice ? "Cart Invoice" : "Transaction Details"}
          </h2>
          <div className="flex items-center gap-2">
            <Button variant="ghost" size="sm" onClick={handlePrint}>
              <Printer className="h-4 w-4" />
            </Button>
            <Button variant="ghost" size="sm" onClick={handlePrint}>
              <Download className="h-4 w-4" />
            </Button>
            <Button variant="ghost" size="sm" onClick={onClose}>
              <X className="h-4 w-4" />
            </Button>
          </div>
        </div>

        <div ref={printRef} className="px-5 py-4">
          {withdrawal ? (
            <div className="space-y-1">
              <DetailRow label="ID" value={withdrawal.id} mono />
              <DetailRow label="Amount" value={formatCurrency(withdrawal.amount)} />
              <DetailRow label="Status" value={statusLabel[withdrawal.status] || withdrawal.status} />
              <DetailRow label="Destination Bank" value={withdrawal.destinationBank || "—"} />
              <DetailRow label="Account Number" value={withdrawal.destinationAccount || "—"} mono />
              <DetailRow label="Account Name" value={withdrawal.accountName || "—"} />
              <DetailRow label="Narration" value={withdrawal.narration || "—"} />
              <DetailRow label="Reference" value={withdrawal.reference || "—"} mono />
              {withdrawal.monnifyRef && <DetailRow label="Monnify Ref" value={withdrawal.monnifyRef} mono />}
              <DetailRow label="Created" value={formatDateTime(withdrawal.createdAt)} />
              {withdrawal.processedAt && <DetailRow label="Processed" value={formatDateTime(withdrawal.processedAt)} />}
            </div>
          ) : transaction ? (
            isInvoice && !loadingInvoice ? (
              <div className="space-y-4">
                <div className="border-b border-neutral-200 pb-3">
                  <h3 className="text-lg font-bold text-neutral-900">{companyName}</h3>
                  <p className="text-sm text-neutral-500">Cart Purchase Invoice</p>
                  <p className="mt-1 text-xs text-neutral-400">Ref: {transaction.reference || transaction.id.substring(0, 8).toUpperCase()}</p>
                  <p className="text-xs text-neutral-400">Date: {formatDateTime(transaction.createdAt)}</p>
                </div>

                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-neutral-300 text-xs text-neutral-500">
                      <th className="pb-2 text-left font-medium">Item</th>
                      <th className="pb-2 text-right font-medium">Amount</th>
                    </tr>
                  </thead>
                  <tbody>
                    {bookingItems.map((item) => (
                      <tr key={item.id} className="border-b border-neutral-100">
                        <td className="py-2 text-neutral-900">{item.title}</td>
                        <td className="py-2 text-right font-mono text-neutral-900">{formatCurrency(item.totalCost)}</td>
                      </tr>
                    ))}
                  </tbody>
                  <tfoot>
                    <tr className="border-t-2 border-neutral-900">
                      <td className="pt-2 text-sm font-bold text-neutral-900">Total</td>
                      <td className="pt-2 text-right font-mono text-sm font-bold text-neutral-900">{formatCurrency(transaction.amount)}</td>
                    </tr>
                  </tfoot>
                </table>

                {branding?.contactAddress && (
                  <p className="text-xs text-neutral-400">{branding.contactAddress}</p>
                )}
              </div>
            ) : loadingInvoice ? (
              <p className="py-4 text-center text-sm text-neutral-400">Loading invoice details...</p>
            ) : (
              <div className="space-y-1">
                <DetailRow label="ID" value={transaction.id} mono />
                <DetailRow label="Type" value={transaction.type || "—"} />
                <DetailRow label="Amount" value={`${transaction.type === "CREDIT" ? "+" : "−"}${formatCurrency(transaction.amount)}`} />
                <DetailRow label="Description" value={transaction.description || "—"} />
                <DetailRow label="Reference" value={transaction.reference || "—"} mono />
                {transaction.monnifyRef && <DetailRow label="Monnify Ref" value={transaction.monnifyRef} mono />}
                <DetailRow label="Balance Before" value={transaction.balanceBefore != null ? formatCurrency(transaction.balanceBefore) : "—"} />
                <DetailRow label="Balance After" value={transaction.balanceAfter != null ? formatCurrency(transaction.balanceAfter) : "—"} />
                <DetailRow label="Date" value={formatDateTime(transaction.createdAt)} />
              </div>
            )
          ) : null}
        </div>
      </div>
    </div>
  );
}
