"use client";

import { useParams } from "next/navigation";
import { useEffect, useState, useRef } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Printer, Download } from "lucide-react";

interface Booking {
  id: string;
  startDate: string;
  endDate: string;
  totalCost: number;
  currency: string;
  status: string;
  purpose: string | null;
  pickupLocation: string | null;
  dropoffLocation: string | null;
  clientNote: string | null;
  ownerNote: string | null;
  createdAt: string;
  asset: { id: string; title: string; type: string; plateNumber: string | null };
  owner: { id: string; fullName: string; email: string; phone: string | null };
}

export default function InvoicePage() {
  const params = useParams();
  const [booking, setBooking] = useState<Booking | null>(null);
  const [loading, setLoading] = useState(true);
  const [branding, setBranding] = useState({ companyName: "TruckLease Pro", appName: "TruckLease Pro", logoUrl: null as string | null, contactAddress: "42 Awolowo Road, Ikoyi, Lagos" });
  const printRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    Promise.all([
      fetch(`/api/bookings/${params.id}`).then((r) => r.json()),
      fetch("/api/settings/public").then((r) => r.json()),
    ]).then(([bRes, sRes]) => {
      if (bRes.success) setBooking(bRes.data);
      if (sRes.success) setBranding(sRes.data);
    }).finally(() => setLoading(false));
  }, [params.id]);

  function handlePrint() {
    window.print();
  }

  function handleDownloadPdf() {
    const content = printRef.current?.innerHTML || "";
    const printWin = window.open("", "_blank");
    if (!printWin) return;
    printWin.document.write(`
      <html><head><title>Invoice #${booking?.id.slice(0, 8).toUpperCase()}</title>
      <style>
        body { font-family: 'Courier New', monospace; padding: 40px; font-size: 13px; color: #1a1a1a; }
        table { width: 100%; border-collapse: collapse; }
        td, th { padding: 8px; text-align: left; border-bottom: 1px solid #e5e5e5; }
        th { background: #fafafa; font-weight: 600; }
        .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #1a1a1a; padding-bottom: 16px; margin-bottom: 24px; }
        .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e5e5e5; text-align: center; font-size: 11px; color: #a3a3a3; }
        .right { text-align: right; }
        .bold { font-weight: 700; }
      </style></head><body>
      ${content}
      <div class="footer">Generated by ${branding.companyName} on ${new Date().toLocaleDateString()}</div>
      </body></html>
    `);
    printWin.document.close();
    setTimeout(() => printWin.print(), 500);
  }

  if (loading) return <div className="flex min-h-[60vh] items-center justify-center"><div className="h-8 w-8 animate-spin rounded-full border-2 border-neutral-200 border-t-primary" /></div>;
  if (!booking) return <div className="py-12 text-center text-sm text-neutral-500">Booking not found.</div>;

  const start = new Date(booking.startDate);
  const end = new Date(booking.endDate);
  const days = Math.max(1, Math.ceil((end.getTime() - start.getTime()) / (1000 * 60 * 60 * 24)));
  const dailyRate = booking.totalCost / days;

  return (
    <div className="mx-auto max-w-3xl">
      <div className="mb-4 flex items-center justify-between print:hidden">
        <h1 className="text-2xl font-bold text-neutral-900">Invoice</h1>
        <div className="flex gap-2">
          <Button variant="outline" onClick={handleDownloadPdf}><Download className="mr-2 h-4 w-4" /> PDF</Button>
          <Button onClick={handlePrint}><Printer className="mr-2 h-4 w-4" /> Print</Button>
        </div>
      </div>

      <div ref={printRef} className="rounded-lg border border-neutral-200 bg-white p-8 shadow-sm">
        <div className="flex items-center justify-between border-b border-neutral-200 pb-6">
          <div>
            <div className="flex items-center gap-2">
              {branding.logoUrl ? (
                <img src={branding.logoUrl} alt="" className="h-8 w-8 rounded object-contain" />
              ) : (
                <div className="flex h-8 w-8 items-center justify-center rounded bg-primary">
                  <span className="text-sm font-bold text-white">TL</span>
                </div>
              )}
              <span className="font-heading text-xl font-bold text-neutral-900">{branding.companyName}</span>
            </div>
            <p className="mt-1 text-sm text-neutral-500">{branding.contactAddress}</p>
          </div>
          <div className="text-right">
            <p className="text-2xl font-bold text-neutral-900">INVOICE</p>
            <p className="text-sm text-neutral-500">#{booking.id.slice(0, 8).toUpperCase()}</p>
          </div>
        </div>

        <div className="mt-6 grid grid-cols-2 gap-6">
          <div>
            <p className="text-xs font-medium uppercase tracking-wider text-neutral-400">Bill To</p>
            <p className="mt-1 text-sm font-medium text-neutral-900">{booking.owner.fullName}</p>
            <p className="text-sm text-neutral-600">{booking.owner.email}</p>
            {booking.owner.phone && <p className="text-sm text-neutral-600">{booking.owner.phone}</p>}
          </div>
          <div className="text-right">
            <p className="text-xs font-medium uppercase tracking-wider text-neutral-400">Invoice Date</p>
            <p className="mt-1 text-sm text-neutral-900">{new Date(booking.createdAt).toLocaleDateString("en-NG", { year: "numeric", month: "long", day: "numeric" })}</p>
            <p className="mt-3 text-xs font-medium uppercase tracking-wider text-neutral-400">Payment Due</p>
            <p className="mt-1 text-sm text-neutral-900">{new Date(booking.startDate).toLocaleDateString("en-NG", { year: "numeric", month: "long", day: "numeric" })}</p>
          </div>
        </div>

        <div className="mt-8 overflow-hidden rounded-lg border border-neutral-200">
          <table className="w-full text-left text-sm">
            <thead>
              <tr className="bg-neutral-50">
                <th className="px-4 py-3 font-medium text-neutral-500">Description</th>
                <th className="px-4 py-3 font-medium text-neutral-500">Rate</th>
                <th className="px-4 py-3 font-medium text-neutral-500">Days</th>
                <th className="px-4 py-3 text-right font-medium text-neutral-500">Amount</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-neutral-100">
              <tr>
                <td className="px-4 py-3">
                  <p className="font-medium text-neutral-900">{booking.asset.title}</p>
                  <p className="text-xs text-neutral-400">{booking.asset.type}{booking.asset.plateNumber ? ` \u2022 ${booking.asset.plateNumber}` : ""}</p>
                  {booking.purpose && <p className="text-xs text-neutral-400">{booking.purpose}</p>}
                </td>
                <td className="px-4 py-3 text-neutral-700">&#x20A6;{dailyRate.toLocaleString("en-US", { minimumFractionDigits: 2 })}/day</td>
                <td className="px-4 py-3 text-neutral-700">{days}</td>
                <td className="px-4 py-3 text-right font-mono text-neutral-900">&#x20A6;{booking.totalCost.toLocaleString("en-US", { minimumFractionDigits: 2 })}</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="mt-4 flex justify-end">
          <div className="w-64 space-y-1.5 text-sm">
            <div className="flex justify-between text-neutral-600">
              <span>Subtotal</span>
              <span>&#x20A6;{booking.totalCost.toLocaleString("en-US", { minimumFractionDigits: 2 })}</span>
            </div>
            <div className="flex justify-between border-t border-neutral-200 pt-1.5 text-base font-bold text-neutral-900">
              <span>Total</span>
              <span>&#x20A6;{booking.totalCost.toLocaleString("en-US", { minimumFractionDigits: 2 })}</span>
            </div>
          </div>
        </div>

        {booking.pickupLocation && (
          <div className="mt-6 border-t border-neutral-200 pt-4 text-sm text-neutral-600">
            <p><span className="font-medium text-neutral-700">Pickup:</span> {booking.pickupLocation}</p>
            {booking.dropoffLocation && <p className="mt-0.5"><span className="font-medium text-neutral-700">Dropoff:</span> {booking.dropoffLocation}</p>}
          </div>
        )}

        <div className="mt-6 border-t border-neutral-200 pt-4 text-center text-xs text-neutral-400">
          <p>{branding.companyName} — Nigeria&apos;s trusted platform for truck &amp; equipment leasing</p>
          <p className="mt-0.5">Thank you for your business!</p>
        </div>
      </div>
    </div>
  );
}
